// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'main.dart';

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/home',
        uri: Uri.parse('/home'),
        routeBuilder: b0Builder,
      ),
      RouteEntity(
        key: '/splash',
        uri: Uri.parse('/splash'),
        routeBuilder: b1Builder,
      ),
      RouteEntity(
        key: '/register_app',
        uri: Uri.parse('/register_app'),
        routeBuilder: b2Builder,
      ),
    ];

const routePaths = (
  path: '/',
  home: '/home',
  splash: '/splash',
  registerApp: '/register_app',
);
